import mongoose from "mongoose";

export const orderItemSchema = new mongoose.Schema({
    // schema externally created.
    //productId automatically generated by mongo    
    productId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User"
    },
    quantity: {
        type: Number,
        required: true,
    },
});
